name: ase-nb-environment
channels:
  - conda-forge
dependencies:
  - python =3.7
  - ase >=3.18,<4
  - attrs >=19,<20
  - importlib_resources >=1,<2
  - matplotlib >=3.1,<4
  - numpy >=1.16
  - python >=3.5
  - pythreejs >=2.1,<3
  - svgutils >=0.3,<0.4
  - svgwrite >=1.3,<2
